Update and add dissociation terms
HUPO-PSI/psi-ms-CV pull request #108
Opened 2022-03-11 15:19 UTC by edeutsch

2022-03-11 15:35 UTC, mobiusklein requested changes

2022-03-11 15:35 UTC, mobiusklein commented on psi-ms.obo
> +def: "A process to fragment ions in a mass spectrometer by inducing fragmentation of anions (e.g. peptides or proteins) by transferring electrons to a radical-cation." [DOI:10.1016/j.jasms.2005.01.01
The source of the definition should be a comma separated list enclosed in square braces:

```suggestion
def: "A process to fragment ions in a mass spectrometer by inducing fragmentation of anions (e.g. peptides or proteins) by transferring electrons to a radical-cation." [DOI:10.1016/j.jasms.2005.01.015, PSI:MS]
```

2022-03-11 15:35 UTC, mobiusklein commented on psi-ms.obo
> +def: "A process transfer of one or more protons from a multiply charged cation (peptide or protein ion) to an anionic agent, that typically does not lead to fragmentation" [DOI: 10.1002/mas.20048] [P
```suggestion
def: "A process transfer of one or more protons from a multiply charged cation (peptide or protein ion) to an anionic agent, that typically does not lead to fragmentation" [DOI: 10.1002/mas.20048, PSI:MS]
```

2022-03-11 16:17 UTC, mobiusklein commented on psi-ms.obo
> +def: "A process to fragment ions in a mass spectrometer by inducing fragmentation of cations (e.g. peptides or proteins) by transferring electrons from radical-anions." [DOI: 10.1073/pnas.0402700101,
```suggestion
def: "A process to fragment ions in a mass spectrometer by inducing fragmentation of cations (e.g. peptides or proteins) by transferring electrons from radical-anions." [DOI: 10.1073/pnas.0402700101, PMID: 15210983, PSI:MS]
```

2022-03-11 16:22 UTC, mobiusklein commented
Remaining ambiguity over whether the last two terms are "precursor activation" vs "dissociation method" which makes them separate.

2022-03-11 16:43 UTC, chambm commented
Dissociation method is:
relationship: part_of MS:1000456 ! precursor activation

Making the PTR terms direct is_a to precursor activation would make the relationships different.

But why don't we consider PTR to be an ionization method instead of an activation method?

2022-03-12 18:02 UTC, edeutsch commented
> But why don't we consider PTR to be an ionization method instead of an activation method?

I do not really know enough about PTR to say for sure, but what you suggest seems better. Appealing to @jshofstahl  and @pabinz for another opinion. Should
- proton transfer reaction
- negative proton transfer reaction
be children of MS:10000008 ionization type instead? See existing children here: (click on + to expand):
https://www.ebi.ac.uk/ols/ontologies/ms/terms?iri=http%3A%2F%2Fpurl.obolibrary.org%2Fobo%2FMS_1000008

2022-03-15 09:53 UTC, pabinz commented
To my understanding,

PTR-MS is originally designed to analyse volatile compounds. In this method a proton is transfered from a hydronium ion (H3O+) to a neutral analyte, leading to a protonated analyte. 

In proteomics, for instance in top down approach, ion/ion proton transfer (also named PTR) is used to reduce the number of protons attached to a multiply charge protein ion (and therefore simplifiy the ion cluster of a proteoform. The mechanism involves the presence of proton acceptors anions or neutral basic compounds that can capture protons from mutiply protonated protein ions. It is also used, in combination with ETD as fragmentation method, to target a reduction of the the complexity of the ion clusters in fragmentation spectra. In that respect, I would not consider it as activation method either.

PTR per se is not inducing fragmentation. 
In our CV, the use of the word activation is coupled with a dissociation/fragmentation event (CID, HCD, ETD, etc.).

Therefore PTR should be considered as an ionisation method and not an activation method.

And the definition should also consider a more generic description of a reaction that transfers one or more proton from a protonated molecule to a neutral or anionic proton acceptor species.

2022-03-15 14:55 UTC, jshofstahl commented
I was able to discuss the terms with John Syka yesterday and he did mention that PTR isn't the preferred name at this point due to the reason that Pierre-Alain mentioned.  We have switched to use Protein Transfer Charge Reduction (PTCR) for the technique in our documentation.  Some software still shows PTR inn the data but that is because they haven't switched to newer builds of our common components libraries.

2022-03-21 18:32 UTC, edeutsch commented
Based on the conversation, I have updated the PR to read like this now: Is that correct?

```
[Term]
id: MS:1003247
name: proton transfer reaction
def: "A process to transfer a proton from a hydronium ion (H3O+) to neutral analyte, leading to a protonated analyte, which typically does not lead to fragmentation" [DOI:10.1002/mas.20048, PSI:MS]
synonym: "PTR" EXACT []
is_a: MS:1000008 ! ionization type

[Term]
id: MS:1003248
name: proton transfer charge reduction
def: "A process to transfer of one or more protons from a multiply charged cation (peptide or protein ion) to a proton acceptor anion or neutral basic compound" [PSI:MS]
synonym: "PTCR" EXACT []
is_a: MS:1000008 ! ionization type
```

2022-03-21 18:39 UTC, edeutsch commented
Slight further edits. Comments?

```
[Term]
id: MS:1003247
name: proton transfer reaction
def: "Process to transfer a proton from a hydronium ion (H3O+) to neutral analyte, leading to a protonated analyte, which typically does not lead to fragmentation." [DOI:10.1002/mas.20048, PSI:MS]
synonym: "PTR" EXACT []
is_a: MS:1000008 ! ionization type

[Term]
id: MS:1003248
name: proton transfer charge reduction
def: "Process to transfer one or more protons from a multiply charged cation (peptide or protein ion) to a proton acceptor anion or neutral basic compound, thereby reducing the charge of the original analyte." [PSI:MS]
synonym: "PTCR" EXACT []
is_a: MS:1000008 ! ionization type
```

2022-03-21 21:36 UTC, jshofstahl commented
The most recent change from Eric looks OK to me.

2022-03-21 21:51 UTC, mobiusklein approved these changes

2022-03-24 02:29 UTC, merged