Add electron activated dissociation and SCIEX ZenoTOF
HUPO-PSI/psi-ms-CV pull request #159
Opened 2022-09-22 01:38 UTC by mobiusklein

Closes #158

2022-09-22 01:39 UTC, mobiusklein commented
@meier-rene Please check if this satisfies your definition request.

2022-09-22 07:51 UTC, meier-rene commented
Thank you. That's fine.

2022-09-23 06:10 UTC, edeutsch requested changes
I think the company name is just plain SCIEX now, so I would suggest we drop the "Applied Biosystems/MDS" as that is obsolete I think (for this instrument).

otherwise looks great.

2022-09-23 14:59 UTC, edeutsch approved these changes

2022-09-23 15:11 UTC, merged