Fix inconsistent QC metrics
HUPO-PSI/psi-ms-CV pull request #234
Opened 2024-01-26 15:18 UTC by bittremieux

Fixes #226. Fixes #227.

2024-01-26 16:13 UTC, mobiusklein requested changes
Minor syntax

2024-01-26 16:13 UTC, mobiusklein commented on psi-ms.obo
> +relationship: has_metric_category: MS:4000008 ! ID based
I don't think relationship labels terminate with `:`

```
relationship: has_units UO:0000021 ! gram
relationship: has_value_type xsd:float ! The allowed value-type for this CV term
```

2024-01-27 21:00 UTC, mobiusklein approved these changes

2024-02-08 16:32 UTC, mwalzer commented
:+1:

2024-02-09 04:50 UTC, edeutsch approved these changes
Looks pretty good except that MS:4000008 is an "ID based metric", not an "ID based"

2024-02-09 15:58 UTC, edeutsch approved these changes

2024-02-09 16:19 UTC, merged