add precursor ppm accuracy and precision
HUPO-PSI/psi-ms-CV pull request #254
Opened 2024-04-08 11:34 UTC by cbielow

fixes  #241

I've opted to add a `precision` term, which I'm not sure is needed, but since there is `accuracy` already, I thought there is no harm.
However, those two terms are rather narrow, but maybe that's ok. I used a free ID slot (MS:1000394).
We can also remove the precision annotation if desired. I have no strong opinion, but I think may add some helpful context.

2024-04-11 13:55 UTC, mwalzer commented
Maybe align the name wording to the other distribution parameter QC metric terms? 
e.g. MS:4000108 and [MS:4000109](https://github.com/HUPO-PSI/psi-ms-CV/blob/24dfb9733249e1814cee79cfd55642233b28c543/psi-ms.obo#L23321)

2024-04-12 13:26 UTC, mwalzer commented
:+1:

2024-04-12 15:16 UTC, edeutsch reviewed
Our custom is to have names like:
  precursor ppm deviation mean
  precursor ppm deviation standard deviation
instead of terms that include "of"

2024-04-14 11:35 UTC, bittremieux requested changes
@cbielow Can you make the naming changes that Eric requested? Other than that it looks good to me.

2024-04-14 18:24 UTC, bittremieux approved these changes

2024-04-14 18:24 UTC, bittremieux requested changes

2024-04-14 18:24 UTC, bittremieux commented on psi-ms.obo
> +<<<<<<< HEAD
Can you fix the merge conflicts here?

2024-04-14 18:27 UTC, cbielow commented
should be good to go now

2024-04-15 13:01 UTC, bittremieux approved these changes

2024-04-19 15:11 UTC, edeutsch approved these changes

2024-04-19 17:03 UTC, merged