Added new terms for pyteomics and ThermoRawFileParser
HUPO-PSI/psi-ms-CV pull request #57
Opened 2021-02-01 18:54 UTC by caetera

2021-02-02 05:25 UTC, edeutsch requested changes
Just to be a little more complete, would you replace the [PSI-MS] with a PMID and/or a DOI like in other terms like this, e.g.:

[Term]
id: MS:1001969
name: phosphoRS score
def: "phosphoRS score for PTM site location at the PSM-level." [DOI:10.1021/pr200611n, PMID:22073976]
xref: value-type:xsd\:string "The allowed value-type for this CV term."
is_a: MS:1001968 ! PTM localization PSM-level statistic
relationship: has_regexp MS:1002505 ! regular expression for modification localization scoring

2021-02-03 00:30 UTC, edeutsch approved these changes
looks great, thanks!

2021-02-15 11:02 UTC, caetera commented
Hi Eric,

do you know when the suggestion will be merged into the ontology? It would be nice if we can add it to the release of TRFP that is in preparation now.

2021-02-15 16:41 UTC, chambm approved these changes

2021-02-15 16:42 UTC, merged