fix/issue59
HUPO-PSI/psi-ms-CV pull request #60
Opened 2021-03-05 14:57 UTC by mtrobey

Fixes a typo in MS:1003130 - the wrong ID was used in the parent term line. This was an error in the original PR #47.

2021-03-05 16:00 UTC, chambm approved these changes

2021-03-05 16:02 UTC, chambm commented
Hmm, why revert the version? I think even a revision like this should probably bump the final number.

2021-03-05 16:05 UTC, mtrobey commented
It looks like the last few issue fix PRs haven't updated the version - let me know if you think I should update it though!

2021-03-05 16:12 UTC, chambm commented
@edeutsch ?

2021-03-05 17:21 UTC, edeutsch requested changes
yes, please do bump the version number up by one and then we'll merge. Looking at the commit history, it looks like we have been pretty good about this. I don't see a reason to make any change without increasing the version number, especially one that moves a term to a new parent, even fixing an error.

2021-03-05 17:28 UTC, merged

2021-03-05 17:30 UTC, edeutsch commented
thanks everyone!

2021-03-08 16:51 UTC, timosachsenberg commented
Thanks. I will check and report back.